'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<System.ComponentModel.DataAnnotations.MetadataTypeAttribute(GetType(PhaseMetadata))>
Partial Public Class Phase
    Public Property Id As Integer
    Public Property Description As String
    Public Property date_created As Date

    Public Overridable Property PhaseProcesses As ICollection(Of PhaseProcess) = New HashSet(Of PhaseProcess)

End Class
