'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ptero_User
    Public Property Id As Integer
    Public Property first_name As String
    Public Property last_name As String
    Public Property user_email As String
    Public Property date_created As Date

    Public Overridable Property ComponentUsers As ICollection(Of ComponentUser) = New HashSet(Of ComponentUser)
    Public Overridable Property Processusers As ICollection(Of Processuser) = New HashSet(Of Processuser)
    Public Overridable Property UserRoles As ICollection(Of UserRole) = New HashSet(Of UserRole)

End Class
