'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Models
    Partial Public Class Role
        Public Property Id As Integer
        Public Property Description As Integer
        Public Property date_created As Date

        Public Overridable Property UserRoles As ICollection(Of UserRole) = New HashSet(Of UserRole)

    End Class
End Namespace